name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run deploy
        run: |
          cd /home/abiscula/proxmox-dashboard
          chmod +x deploy.sh
          ./deploy.sh
